server:
  port: 8081

raif:
  sbpMerchantId: "MA622976"
  secretKey: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNQTYyMjk3NiIsImp0aSI6ImM5MTBjNGU4LTRhZmMtNDBlMS04ZGU3LWVlODg2N2JiOGU3NCJ9.rnPFEsixy9Wr4GhxT9D9s8dlBg5dRKWMLPfxl48oHAo"

notification:
  callback:
    value: "https://pay-test.raif.ru/api/settings/v1/callback"
  url:
    value: "http://localhost:8081/payment-api/v1/notification"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/first_db?currentSchema=payment
    username: postgres
    password: 1488
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/db.changelog-1.0.yaml
    enabled: true
    default-schema: payment
  task:
    scheduling:
      pool:
        size: 2