version: '3'

services:
  app:
    image: payment_app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment_app
    ports:
      - '8081:8081'
    environment:
      - SERVER_PORT= 8081