version: '3'

services:
  app:
    image: database_app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: database_app
    depends_on:
      - db
    ports:
      - '9091:9091'
    environment:
      - SERVER_PORT= 9091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/first_db
  db:
    image: postgres:15.1-alpine
    container_name: database_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1488
      - POSTGRES_DB=first_db
    ports:
      - '5432:5432'