version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: database_app
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - '9091:9091'
  db:
    image: postgres:15.1-alpine
    container_name: database_postgres
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1488
      - POSTGRES_DB=first_db
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d